### ISSUE TITLE
ERROR: Could not allocate a buffer for target

### ISSUE THREAD

**Issue by yanivetrogi** [microsoft/diskspd#135]
When specifying a block size of 256 and up I receive this error.
I verified it happens on Windows Server 2016 and 2019
I am using the latest version of diskspd. 

diskspd.exe -c1024M -w0 -t8 -d60 -o128 -r -b512K -C1 -Z1G -W1 -L -h "B:\temp\Diskspd\diskspdtest.dat"

ERROR: Could not allocate a buffer for target 'B:\temp\Diskspd\diskspdtest.dat'. Error code: 0x8
There has been an error during threads execution
Error generating I/O requests

**Comment by DanPear** [comment]
An error code of 0x8 maps to there not enough memory resources available to process the command. I would suggest removing the -Z option if it's not needed or reduce it to something significantly smaller.

Please see issue #126 for further information on using the -Z option.

**Comment by yanivetrogi** [comment]
Thanks for your quick reply
Omitting the -Z parameter now allows using a block size of 512 (-b512K) but fails on 1024.
Is there any other advice?

**Comment by DanPear** [comment]
Sorry, I missed the error you posted above. The -Z option isn't needed in your case as the workload is set to 100 percent reads. The problem you're facing is that we create both read and write buffers for each of the targets based on the block size and the request count even if the percentage of reads or writes is zero.

The call to VirtualAlloc is failing as your system has insufficient resources to fulfill the request. You either need to reduce the block size or the number of outstanding I/O requests used with the -o option.

You should also check that the architecture of the executable matches your platform. The 64-bit version is contained within the amd64 directory and should be used on Windows Server.

**Comment by dl2n** [comment]
I was about to say the same. Also let me repeat back what your command line is now.

diskspd.exe -c1024M -w0 -t8 -d60 -o128 -r -b512K -C1 -W1 -L -h "B:\temp\Diskspd\diskspdtest.dat"

This specifies 8 threads issuing a target of 128 1 MiB IOs each. That’s a queue depth of 1024 IOs and 1 GiB of total queued IO operations. As DanP says DISKSPD is over-allocating for these IOs (2GiB: something that could be addressed), and if your system is 32bit this is likely exactly what the issue is. However, it is unlikely your storage requires anywhere near this amount to saturate and achieve maximum bandwidth, certainly with large IOs.

Try -t8 -o4, and then add to the queue depth in small increments. I believe you’ll see maximums before -o16. Then look at the latencies and explore how queue depth affects them, and consider thinning out the number of threads and queue depth to arrive at a total queue depth which is “just about right” for reaching maximum with moderate latency.

This is a pattern of analysis that’s common, and why the buffer allocation behavior is rarely a limit (even on 32bit systems).

**Comment by yanivetrogi** [comment]
Thanks you both! for the detailed information.
I used now the 64bit (amd64) version and was able to go up to a block size of 8192 with no failure. So yes using the 32 bit version is surly limited and that's understood.
Is there a any reference you can pointy me to to learn more on stress tests?

**Comment by DanPear** [comment]
That's great news. If you haven't taken a look already, the [wiki](https://github.com/microsoft/diskspd/wiki) is a great place to start.

**Comment by yanivetrogi** [comment]
Excellent, i have gone over the wiki which was very usefull.
