### ISSUE TITLE
Huge difference in results between Diskspd.exe versions

### ISSUE THREAD

**Issue by SQLtattoo** [microsoft/diskspd#136]
Hello, 
 just downloaded today the 2.0.21a version, I was using till today the 2.0.17a. I run a test to compare the results from these 2 versions, on my laptop, and I get quite a big difference for the same set of parameters. Attached if interested.

Is this an expected behavior? I mean, I don't know which to trust.

Thanks!
Vassilis

[diskSpeed_v2.0.17a.txt](https://github.com/microsoft/diskspd/files/4470148/diskSpeed_v2.0.17a.txt)
[diskSpeed_v2.0.21a.txt](https://github.com/microsoft/diskspd/files/4470149/diskSpeed_v2.0.21a.txt)

**Comment by SQLtattoo** [comment]
I think I see where the problem lays. I have -t8 while my i7 has 4 cores and while the .17 version yields 3.1 Avg Lat while .21 version gives 11.5 it seems that .17v is cheating.
If I run this with -t4 as per my core count, v.2.0.21a gives a better score -almost 2.4 times better- as attached.

Is this correct?
[diskSpeed_v2.0.17a-t4.txt](https://github.com/microsoft/diskspd/files/4470208/diskSpeed_v2.0.17a-t4.txt)
[diskSpeed_v2.0.21a-t4.txt](https://github.com/microsoft/diskspd/files/4470209/diskSpeed_v2.0.21a-t4.txt)

Vassilis

**Comment by dl2n** [comment]
Sorry for not catching this as it came in.

Running more threads than cores (-t8 on a 4c system) is indeed usually not going to help. The only way it really could is if, somehow, an IO thread had to pend behind synchronization or some other resource before dispatching the IO into the device stack. Otherwise we expect to be running in and out of the kernel and then waiting for the response, asynchronously. Of course DISKSPD is an ideal tool for finding such issues ... if -t8 _did_ help that would be curious and interesting on a 4c system.

What's more likely happening here is a matter of device warmup, the order in which you ran the tests, and then possibly the fact it was run write-through.

Warmup: an SSD is very dynamic under write loads. The flash management layer in the device firmware is usually grooming writeable regions that can quickly land some quantity of burst writes. Especially in consumer devices this burst space may be small and once exhausted, writes will pend behind management operations to create/rebalance space in the SSD for new data.

The way around this is with warmup or simply running longer and watching what happens over time, not just the whole-run average. You're running for only 30s - if there's any reason to suspect device warmup, 5 minutes is generally where we start.

Second, this is a consumer device. If it is actually honoring the write-through request (you are running -Sh, equivalent to -Suw, and the 'w' is what I'm referring to) and writing all the way through into the NAND flash, that is actually a very expensive operation. Alternatively, and this is what we might be hoping for, is that the device could ignore the write-through request and terminate the write into its RAM buffer ... since it is in a laptop and we have power safety from the laptop's battery .... as long as it doesn't fail ... you get the idea.

In enterprise-class SSDs, this is where PLP (power loss protection) comes in, these days usually in the solid-state form of an ultracapacitor or similar. The function of the PLP is to guarantee the device can destage the RAM buffer safely in the event of external power loss, saving all acknowledged writes. In the consumer device without PLP and <pzzt> the battery/power source fails, there is indeed risk of some arbitrary data loss. In the early SSD era there were SSDs which could corrupt their internal metadata and brick themselves in these cases (not so much now).

This article I wrote a few years ago has a straight-through take on some of those issues. Bottom line - if you see a dramatic difference in performance by running only -Su (not -Sh / -Suw) ... this is what you're seeing. A device which is honoring the write-through flag, and exposing some interesting design details.

[Don't do it: consumer-grade solid-state drives (SSD) in Storage Spaces Direct](https://techcommunity.microsoft.com/t5/storage-at-microsoft/don-t-do-it-consumer-grade-solid-state-drives-ssd-in-storage/ba-p/425914)

**Comment by dl2n** [comment]
Closing old issue likely related to order of operations.
