### ISSUE TITLE
[Question] Performance is changing with respect to the order of IO workload.

### ISSUE THREAD

**Issue by raeesulasad** [microsoft/diskspd#138]
Hi ,

To begin with, this is not a bug , but rather a question - posting it here, since I could not find other way to reach out to the community.
I was running the diskspd on an unformatted drive (ZVol disk) with multiple workloads for bench marking of performance. 
I could see completely different results(IOPS,Latency,Throughput) with same workload at different time.   
It would be great if someone can help me  to understand the importance of order of execution of each workload in consistency of diskspd output .

I am using mainly two workloads 

1)8K workload ( 8k block size, random  IO , with 30% write and 70% read )
command used for 8k workload :-
diskspd.exe -b8K -d120 -o32 -r -t6 -w30 -L -D #4 

2)4K workload ( 4K block size, random IO , with 100% write )  
command used for 4k workload :-
diskspd.exe -b4K -d120 -o32 -r -t6 -w100 -L -D #4 

My observations :-
On an unformatted drive , I ran 8k workload and saw IOPS as 28K from diskspd output. Later I ran 4K workload . Then I ran 8k workload again and saw IOPS as 12K.
I just wanted to know this performance change (IOPS of 28K to 12K) in case of 8K workload is expected or not . Also it would be helpful if someone can suggest any methods to follow to get consistent results in case of same workload and would appreciate some guidance as well.  

Note :: I did not observe this issue when I ran diskspd on physical disk directly (Without creating zpool/zvol on it)
Thanks in advance.

**Comment by dl2n** [comment]
This a better question for the ZVol (TrueNAS?) community. DISKSPD is a tool for applying a workload and getting results we can then reason about to understand the OS/storage subsystem it was running over. I could speculate about storage subsystem characteristics which could make this more or less likely, but it would be speculation.

The only thing that jumps out is that your 8K workload is 70r:30w while your 4K workload is 10% write. You do not comment on the performance of the 4K load.

If disk #4 was freshly created ZVol may be optimizing away the reads (70% of the load) since no data has been written to them yet. As writes occur, this optimization fades out and reads must come from the underlying physical storage (or at least, cannot be optimized away at the highest level of the stack). Running that 4K load will certainly spend all its time filling out data.

One other way to look at this would be if you ran your 8K 70:30 workload several times in a row: I wonder if it would progressively slow down - this would be a strong indication this is what was occurring. You could also look at the per second IOPS either in the XML output (-Rxml) or watch the performance in Performance Monitor - it is quite possible you would be able to see the IOPS declining in realtime over the course of even the first run.

**Comment by dl2n** [comment]
Closing old issue likely related to order of operations.
