### ISSUE TITLE
DISKSPD is not generating any data for higher configuration parameters which results in generating empty xml result files

### ISSUE THREAD

**Issue by rayudu47815** [microsoft/diskspd#147]
Hi ,

> Need to know if there are limitations for the Diskspd tool 

we are trying to run DISKSPD test on our systems and observed that tool is not generating any data for higher configuration parameters .
This is resulting in generating empty xml files .

common parameters passed in each run to  diskspd.exe are `-W2 -d30  -L -Rxml`

Below are the sample list of different  parameters which we are passing to DISKSPD tool.{ number of cores = 56}

`IoSizeOptsKB = [4, 8]`
`BufferedOpts = ["b", "u", "m", "uw"]`
`FileSizeOptsGB = [8]`
`TargetCountOpts = [1, 8]`
`ThreadCountOpts = [F1,F8,F16,F24,F32,F40,F48,F56] ` --> this lists is generated based on number of cores available 
`OutstandingIOsPerThreadOpts = [1, 4]`
`AccessPatternOpts = ["r"]`
`WritePctOpts = [0, 30, 100]`
`AffinityOpts = [True]`
`SocketCountOpts = [0,1]`
`TargetDirs = [D:/,E:/]`

- DISKSPD will run for given each IoSizeOptsKB with all possible combination of remaining parameters .
- Issue is occurring when the loop reaches to higher ThreadCountOpts or TargetCountOpts in the above case it is failing to generate any data for the cases where ` ThreadCountOpts `= `F40,F48,F56`  or `t40,t48,t56` or `TargetCountOpts` = `40,48,56`

Attaching the sample csv file which captures all the data that DISKSPD is returning 

below is one of the many set of parameters where diskspd is failing 
`'IoSizeKB': 4, 'FileSizeGB': 8, 'Threads': 'F40', 'Buffering': 'b', 'OutstandingIOsPerThread': 1, 'WritePct': 0,'AccessPattern': 'r', 'TargetCount': 1, 'SocketCount': 2, 'AffinitizePhysicalCores': True`

**Comment by dl2n** [comment]
There is no CSV attached to this issue.

Is DISKSPD generating any error on these attempts, or is it silently failing with no output? Can you please provide a specific command line which demonstrates the issue rather than the combinations as specified in your tool's syntax? This may be important.

**Comment by rayudu47815** [comment]
Hi,

1) DISKSPD is silently failing with no output.
2) Attached the log file which contains all the parameters which are passed for the failing scenarios.
3) Attached the Excel file which contains the output values of DISKSPD for each set of parameters passed . 
4) These are the sample run-parameters 
`Run parameters:
{'IoSizeKB': 8, 'FileSizeGB': 8, 'Threads': 'F56', 'Buffering': 'uw', 'OutstandingIOsPerThread': 4, 'WritePct': 100, 'AccessPattern': 'r', 'TargetCount': 1, 'SocketCount': 2, 'AffinitizePhysicalCores': True` }


[sweep_nthreads_sharedfiles.xlsx](https://github.com/microsoft/diskspd/files/6810209/sweep_nthreads_sharedfiles.xlsx)
[full_sweep_12C_2021-06-07-2021.log](https://github.com/microsoft/diskspd/files/6810211/full_sweep_12C_2021-06-07-2021.log)

**Comment by dl2n** [comment]
I need to see the actual DISKSPD command as invoked by  your tool. Can you provide that?

For instance, those tool parameters up to TargetCount should likely look like this:

      diskspd.exe -b8k -c8g -F56 -Suw -O4 -w100 -r

And this works on its own. It is the SocketCount and AffinitizePhysicalCores that may be causing the problems. Please provide a sample command line that your tool is using to invoke DISKSPD.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by rayudu47815** [comment]
Hi,

The below is the sample command for which we are seeing this issue .

`diskspd.exe -W5 -d30 -L -Rxml -b512K  -t40 -Sb -o1 -w0 -si512K -ag1,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78 E:\0_tmp.bin`

**Comment by dl2n** [comment]
Is DISKSPD providing any error output? Perhaps your tool is not capturing stderr that and you only see that there is no output on stdout redirected > result.xml?

The likely source of the issue is the -ag<n> parameter. The <n> is a 0-based index to a processor group, which will usually correspond 1:1 with a processor socket unless you have a very large system (more here: [windows numa support](https://docs.microsoft.com/en-us/windows/win32/procthread/numa-support)). In your example you are building a mask to assign 40 threads starting on processor group 1, on alternating cores from 0 to 78. Unless you do in fact have 2 or more processor groups with 79 or more CPU cores/group (which is not possible - Windows KGROUPS, at least as currently exposed, cannot be more than 64 cores wide) ...

DISKSPD will be returning one or more of these errors, similar to this:

ERROR: affinity assignment to group 1; system only has 1 groups (<= remember groups are indexed at 0)
ERROR: affinity assignment to group 0 core 12 not possible; group only has 12 cores (<= as are CPU cores)

These errors are one way to discover the system topology if you don't already know it. There are more direct ways to do this in the platform; one easily scriptable example would be using the win32_computersystem and win32_processor WMI classes via Powershell (Get-CimInstance win32_processor, etc.).

Once past that, make sure you've reasoned about the load. Interlocked sequential 512KiB buffered reads across 40 threads does create a stress on the system, but it is not one that I'm familiar occurring in normal practice. There are many things DISKSPD can do, but not all of them map back to patterns in real workloads.

**Comment by rayudu47815** [comment]
Hi,

After limiting the -ag parameter to maximum number of processors per KGGROUP available , the required test is going through .
Able to generate all the xml files for all the parameters

**Comment by dl2n** [comment]
Thanks for confirming. Was DISKSPD not producing an error in your case? If you can reproduce it _not_ providing an error with 2.1 I'd appreciate the cmdline.
