### ISSUE TITLE
Option -b performs significantly better when running as admin

### ISSUE THREAD

**Issue by VirtualTim** [microsoft/diskspd#149]
When running as an Admin user using `-b4k` will perform ~10x better than running as a non-Admin user.
<details>
  <summary>Non-Admin: diskspd.exe -b4k temp.dat: 119 MiB/s</summary>

```
Command Line: diskspd.exe -b4k temp.dat

Input parameters:

        timespan:   1
        -------------
        duration: 10s
        warm up time: 5s
        cool down time: 0s
        random seed: 0
        path: 'temp.dat'
                think time: 0ms
                burst size: 0
                using software cache
                using hardware write cache, writethrough off
                performing read test
                block size: 4096
                using sequential I/O (stride: 4096)
                number of outstanding I/O operations: 2
                thread stride size: 0
                threads per file: 1
                using I/O Completion Ports
                IO priority: normal

System information:

        computer name: tlander-pc
        start time: 2021/07/12 06:07:57 UTC

Results for timespan 1:
*******************************************************************************

actual test time:       10.01s
thread count:           1
proc count:             16

CPU |  Usage |  User  |  Kernel |  Idle
-------------------------------------------
   0|  21.72%|   2.19%|   19.53%|  78.28%
   1|   2.19%|   1.72%|    0.47%|  97.81%
   2|   4.06%|   3.44%|    0.63%|  95.94%
   3|  55.94%|   0.78%|   55.16%|  44.06%
   4|   2.97%|   0.47%|    2.50%|  97.03%
   5|   5.31%|   3.13%|    2.19%|  94.69%
   6|   4.38%|   1.72%|    2.66%|  95.63%
   7|   4.69%|   1.09%|    3.59%|  95.31%
   8|   2.50%|   1.88%|    0.63%|  97.50%
   9|   1.25%|   0.47%|    0.78%|  98.75%
  10|   2.03%|   1.25%|    0.78%|  97.97%
  11|   4.38%|   1.56%|    2.81%|  95.63%
  12|   2.97%|   0.78%|    2.19%|  97.03%
  13|   1.87%|   0.78%|    1.09%|  98.13%
  14|   2.19%|   0.78%|    1.41%|  97.81%
  15|   1.25%|   0.63%|    0.63%|  98.75%
-------------------------------------------
avg.|   7.48%|   1.42%|    6.06%|  92.52%

Total IO
thread |       bytes     |     I/Os     |    MiB/s   |  I/O per s |  file
------------------------------------------------------------------------------
     0 |      1248501760 |       304810 |     118.96 |   30452.70 | temp.dat (2048MiB)
------------------------------------------------------------------------------
total:        1248501760 |       304810 |     118.96 |   30452.70

Read IO
thread |       bytes     |     I/Os     |    MiB/s   |  I/O per s |  file
------------------------------------------------------------------------------
     0 |      1248501760 |       304810 |     118.96 |   30452.70 | temp.dat (2048MiB)
------------------------------------------------------------------------------
total:        1248501760 |       304810 |     118.96 |   30452.70

Write IO
thread |       bytes     |     I/Os     |    MiB/s   |  I/O per s |  file
------------------------------------------------------------------------------
     0 |               0 |            0 |       0.00 |       0.00 | temp.dat (2048MiB)
------------------------------------------------------------------------------
total:                 0 |            0 |       0.00 |       0.00
```
</details>

<details>
  <summary>Admin: diskspd.exe -b4k temp.dat: 1011 MiB/s</summary>

```
Command Line: diskspd.exe -b4k temp.dat

Input parameters:

        timespan:   1
        -------------
        duration: 10s
        warm up time: 5s
        cool down time: 0s
        random seed: 0
        path: 'temp.dat'
                think time: 0ms
                burst size: 0
                using software cache
                using hardware write cache, writethrough off
                performing read test
                block size: 4096
                using sequential I/O (stride: 4096)
                number of outstanding I/O operations: 2
                thread stride size: 0
                threads per file: 1
                using I/O Completion Ports
                IO priority: normal

System information:

        computer name: tlander-pc
        start time: 2021/07/12 06:08:32 UTC

Results for timespan 1:
*******************************************************************************

actual test time:       10.01s
thread count:           1
proc count:             16

CPU |  Usage |  User  |  Kernel |  Idle
-------------------------------------------
   0| 100.00%|   4.52%|   95.48%|   0.00%
   1|   0.16%|   0.00%|    0.16%|  99.84%
   2|   0.78%|   0.78%|    0.00%|  99.22%
   3|   0.62%|   0.47%|    0.16%|  99.38%
   4|   0.62%|   0.62%|    0.00%|  99.38%
   5|   4.37%|   4.21%|    0.16%|  95.63%
   6|   0.31%|   0.16%|    0.16%|  99.69%
   7|   0.78%|   0.78%|    0.00%|  99.22%
   8|   0.47%|   0.31%|    0.16%|  99.53%
   9|   1.25%|   0.47%|    0.78%|  98.75%
  10|   0.16%|   0.16%|    0.00%|  99.84%
  11|   2.03%|   2.03%|    0.00%|  97.97%
  12|   2.18%|   0.00%|    2.18%|  97.82%
  13|   0.31%|   0.16%|    0.16%|  99.69%
  14|   1.09%|   0.00%|    1.09%|  98.91%
  15|   0.62%|   0.31%|    0.31%|  99.38%
-------------------------------------------
avg.|   7.23%|   0.94%|    6.30%|  92.77%

Total IO
thread |       bytes     |     I/Os     |    MiB/s   |  I/O per s |  file
------------------------------------------------------------------------------
     0 |     10613198848 |      2591113 |    1010.87 |  258782.74 | temp.dat (2048MiB)
------------------------------------------------------------------------------
total:       10613198848 |      2591113 |    1010.87 |  258782.74

Read IO
thread |       bytes     |     I/Os     |    MiB/s   |  I/O per s |  file
------------------------------------------------------------------------------
     0 |     10613198848 |      2591113 |    1010.87 |  258782.74 | temp.dat (2048MiB)
------------------------------------------------------------------------------
total:       10613198848 |      2591113 |    1010.87 |  258782.74

Write IO
thread |       bytes     |     I/Os     |    MiB/s   |  I/O per s |  file
------------------------------------------------------------------------------
     0 |               0 |            0 |       0.00 |       0.00 | temp.dat (2048MiB)
------------------------------------------------------------------------------
total:                 0 |            0 |       0.00 |       0.00
```
</details>

**Comment by dl2n** [comment]
Summary: this strongly looks like you are showing cached v. uncached results as a function of how the file was operated on and total time these runs were (5s warmup + 10s measured duration). If you were to run the non-admin load again after the admin load, I believe you would see the same ~1GiB/s result with CPU core 0 at 100%.

There are a few ways to confirm this.

First: use an unbuffered read IO run (-c<some size larger than 2GiB> -Su) as a throwaway to prepare the file. Then repeat your non-admin case, paying attention to time & rates as I walk through below. It should reproduce your initial non-admin’s rate. Then delete the file, prepare it fresh again, and run the “admin” case. The result should be the same, slower rate since we will have controlled the variability of the cache, and the admin case will be going through the same caching process.

Or, second, warm up long enough for file to get into cache. If we take the estimate of 118GiB/s, 20s would be enough to sweep the 2GiB file into cache.

Note that neither case gives us a truly “blind” way of operating. For better or worse this is normal.

--

Focusing on this one first, the CPU utilization distribution is peculiar. In your non-admin case its splitting between cores 0 and 3 while in the admin is saturated on core 0, which is what I’d normally expect for a single threaded load.

Note that this is running with the OS (“software”) file cache on (effectively -Sb, the default).

Depending how this file was prepared (this is not -c) and run prior to your first result, the first reads will in fact be going all the way to the storage and then getting cached by the OS. I do see the timestamps showing the non-admin running immediately prior to the admin case.

As far as the IO itself: since this is sequential IO, both runs are starting the thread at byte offset 0 and moving forward from there. 2 outstanding 4KiB reads in a single thread will be very sensitive to the latency of the device. If this was a fresh file or at least had not been operated on with cached IO, the performance for the non-admin case does not seem abnormal. Doing the same thing on an enterprise-class U.2 NVMe NAND device I am getting ~16,000 4KiB IOPS (~62MiB/s) with unbuffered read IO (-Su) at a median latency of 120us, 99th at 205us. This is a little higher than I’d like for reads all the way into NAND but is not abnormal even for this class of device.

Your runs are only 5s warmup + 10s measured duration = 15s in length. Note that the during the measured portion of your non-admin run got 304,810 IOs, or just about 1.16GiB of the 2GiB file. Since this is an SSD and it is a read load warmup is generally not going to affect things too much, so the warmup was likely about the same rate. Net of all that the non-admin run would have hit about 1.5  * 1.16 = ~1.75 GiB of the 2GiB file with IO that would then be cached by the OS.

Now, the next “admin” run also has a 5s warmup. At this point the first ~1.75GiB is in cache, so its going to sweep over that fast and then hit the uncached ~0.25GiB remainder of the file. If we take the admin result as – very likely – being an all-in-cache result at about 1GiB/s, that means the 5s warmup would have gotten to the end of the 1.75GiB of cached data (from the non-admin run) in about 1.75s. It then has an additional 3.25s at the ~118MiB/s rate shown in the non-admin run to cache in some more data before the measured portion starts. At that rate it would be able to get about 3.25 * 118MiB/s = 383MiB more into the cache under warmup, and 1.75GiB + 383GiB is > 2GiB with a hundred or so MiB to spare., so the admin run’s warmup is likely to have finished caching the data.

As a result the entire measured portion of the admin run is in filesystem cache. This is what the core distributions strongly indicate too – the non-admin run’s split of cores 0/3 is probably showing us the effect of asynchronous readahead in the filesystem cache manager (to what effect we can speculate – maybe it helped: as I saw my device at ~62MiB/s, readahead might indeed about double it), while in the admin side being 100% saturated on core 0 does mean it was completely CPU bound, as we would expect for staying 100% in cache and not taking any IO to storage.

If you run the loads with -Su for unbuffered IO you should get the same result for each. Perhaps it will be close to my NVMe device at about 62MiB/s, and we can then indeed see the benefit of the cached readahead for this load on your system.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Tim ***@***.***>
Sent: Sunday, July 11, 2021 11:13 PM
To: ***@***.***>
Cc: ***@***.***>
Subject: [microsoft/diskspd] Option -b performs significantly better when running as admin (#149)


When running as an Admin user using -b4k will perform ~10x better than running as a non-Admin user.
Non-Admin: diskspd.exe -b4k temp.dat: 119 MiB/s

Command Line: diskspd.exe -b4k temp.dat



Input parameters:



        timespan:   1

        -------------

        duration: 10s

        warm up time: 5s

        cool down time: 0s

        random seed: 0

        path: 'temp.dat'

                think time: 0ms

                burst size: 0

                using software cache

                using hardware write cache, writethrough off

                performing read test

                block size: 4096

                using sequential I/O (stride: 4096)

                number of outstanding I/O operations: 2

                thread stride size: 0

                threads per file: 1

                using I/O Completion Ports

                IO priority: normal



System information:



        computer name: tlander-pc

        start time: 2021/07/12 06:07:57 UTC



Results for timespan 1:

*******************************************************************************



actual test time:       10.01s

thread count:           1

proc count:             16



CPU |  Usage |  User  |  Kernel |  Idle

-------------------------------------------

   0|  21.72%|   2.19%|   19.53%|  78.28%

   1|   2.19%|   1.72%|    0.47%|  97.81%

   2|   4.06%|   3.44%|    0.63%|  95.94%

   3|  55.94%|   0.78%|   55.16%|  44.06%

   4|   2.97%|   0.47%|    2.50%|  97.03%

   5|   5.31%|   3.13%|    2.19%|  94.69%

   6|   4.38%|   1.72%|    2.66%|  95.63%

   7|   4.69%|   1.09%|    3.59%|  95.31%

   8|   2.50%|   1.88%|    0.63%|  97.50%

   9|   1.25%|   0.47%|    0.78%|  98.75%

  10|   2.03%|   1.25%|    0.78%|  97.97%

  11|   4.38%|   1.56%|    2.81%|  95.63%

  12|   2.97%|   0.78%|    2.19%|  97.03%

  13|   1.87%|   0.78%|    1.09%|  98.13%

  14|   2.19%|   0.78%|    1.41%|  97.81%

  15|   1.25%|   0.63%|    0.63%|  98.75%

-------------------------------------------

avg.|   7.48%|   1.42%|    6.06%|  92.52%



Total IO

thread |       bytes     |     I/Os     |    MiB/s   |  I/O per s |  file

------------------------------------------------------------------------------

     0 |      1248501760 |       304810 |     118.96 |   30452.70 | temp.dat (2048MiB)

------------------------------------------------------------------------------

total:        1248501760 |       304810 |     118.96 |   30452.70



Read IO

thread |       bytes     |     I/Os     |    MiB/s   |  I/O per s |  file

------------------------------------------------------------------------------

     0 |      1248501760 |       304810 |     118.96 |   30452.70 | temp.dat (2048MiB)

------------------------------------------------------------------------------

total:        1248501760 |       304810 |     118.96 |   30452.70



Write IO

thread |       bytes     |     I/Os     |    MiB/s   |  I/O per s |  file

------------------------------------------------------------------------------

     0 |               0 |            0 |       0.00 |       0.00 | temp.dat (2048MiB)

------------------------------------------------------------------------------

total:                 0 |            0 |       0.00 |       0.00
Admin: diskspd.exe -b4k temp.dat: 1011 MiB/s

Command Line: diskspd.exe -b4k temp.dat



Input parameters:



        timespan:   1

        -------------

        duration: 10s

        warm up time: 5s

        cool down time: 0s

        random seed: 0

        path: 'temp.dat'

                think time: 0ms

                burst size: 0

                using software cache

                using hardware write cache, writethrough off

                performing read test

                block size: 4096

                using sequential I/O (stride: 4096)

                number of outstanding I/O operations: 2

                thread stride size: 0

                threads per file: 1

                using I/O Completion Ports

                IO priority: normal



System information:



        computer name: tlander-pc

        start time: 2021/07/12 06:08:32 UTC



Results for timespan 1:

*******************************************************************************



actual test time:       10.01s

thread count:           1

proc count:             16



CPU |  Usage |  User  |  Kernel |  Idle

-------------------------------------------

   0| 100.00%|   4.52%|   95.48%|   0.00%

   1|   0.16%|   0.00%|    0.16%|  99.84%

   2|   0.78%|   0.78%|    0.00%|  99.22%

   3|   0.62%|   0.47%|    0.16%|  99.38%

   4|   0.62%|   0.62%|    0.00%|  99.38%

   5|   4.37%|   4.21%|    0.16%|  95.63%

   6|   0.31%|   0.16%|    0.16%|  99.69%

   7|   0.78%|   0.78%|    0.00%|  99.22%

   8|   0.47%|   0.31%|    0.16%|  99.53%

   9|   1.25%|   0.47%|    0.78%|  98.75%

  10|   0.16%|   0.16%|    0.00%|  99.84%

  11|   2.03%|   2.03%|    0.00%|  97.97%

  12|   2.18%|   0.00%|    2.18%|  97.82%

  13|   0.31%|   0.16%|    0.16%|  99.69%

  14|   1.09%|   0.00%|    1.09%|  98.91%

  15|   0.62%|   0.31%|    0.31%|  99.38%

-------------------------------------------

avg.|   7.23%|   0.94%|    6.30%|  92.77%



Total IO

thread |       bytes     |     I/Os     |    MiB/s   |  I/O per s |  file

------------------------------------------------------------------------------

     0 |     10613198848 |      2591113 |    1010.87 |  258782.74 | temp.dat (2048MiB)

------------------------------------------------------------------------------

total:       10613198848 |      2591113 |    1010.87 |  258782.74



Read IO

thread |       bytes     |     I/Os     |    MiB/s   |  I/O per s |  file

------------------------------------------------------------------------------

     0 |     10613198848 |      2591113 |    1010.87 |  258782.74 | temp.dat (2048MiB)

------------------------------------------------------------------------------

total:       10613198848 |      2591113 |    1010.87 |  258782.74



Write IO

thread |       bytes     |     I/Os     |    MiB/s   |  I/O per s |  file

------------------------------------------------------------------------------

     0 |               0 |            0 |       0.00 |       0.00 | temp.dat (2048MiB)

------------------------------------------------------------------------------

total:                 0 |            0 |       0.00 |       0.00
