### ISSUE TITLE
DiskSpd not providing file version, product name, or product version

### ISSUE THREAD

**Issue by antvan** [Microsoft/diskspd#35]
![diskspd](https://cloud.githubusercontent.com/assets/26718100/24364089/91f003b8-12c6-11e7-9040-a4d049e3b9e1.PNG)

**Comment by dl2n** [comment]
I agree this does look like something worth filling in. If you know how to hook this up to the current versioning #defines, I’d welcome the contribution. I may take a look in the medium, but this doesn’t look like a priority.

Let us know.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by antvan** [comment]
I understand that it's not a breaking issue.  I use the information for reporting purposes, but it's more of an inconvenience than anything else.

**Comment by DanPear** [comment]
Please check the commit, 88d457b8f9360a9379e93e071f34c86ec83af9a4, for a possible solution. The reason for defining individual values is so that both the file version and file version string can be updated with a single change. Without overriding the file version it'll inherit the values defined in the build environment.
