### ISSUE TITLE
DiskSPD not writing to the Drive in chunks as defined by the -b <Blocksize> parameter

### ISSUE THREAD

**Issue by reckerx** [Microsoft/diskspd#62]
Problem Description:
Used DiskSpd CLI commands to perform Sequential write operation on SD/uSD cards connected via Protocol Analyzer.
 
o   Performed write with different Block size ( -b128k, -b256k, -b512k etc.) defined as a parameter to diskspd and captured the trace for each of them, observed no change in the output BlockSize as captured by Protocol Analyzer. 
 
Questions:
 
o   What happens when the DiskSpd –b blocksize parameter is set to custom value (4k, 16k, 64k, 1M etc.) ?
o   Does diskspd write data on the SD/uSD cards in chunks as specified by the –b parameter or is there any intermediate conversion happens either by OS or Hardware which makes the input diskspd –b parameter obsolete ?
o   Any suggestions regarding the tool to be used and the methodologies for testing such transfers and monitoring at what BlockSize data being written to drives and to capture the traces(Using Hardware based Protocol Analyzers). ??

**Comment by dl2n** [comment]
Unless you are using -h or -Sh  for non-cached write-through IO, the IO is going through the filesystem cache. Various effects due to the cache are possible.

What are the cmdlines you are using, and what are your observed IO sizes? I suspect they may be different for reads v. writes, and dependent on the IO pattern and number of threads.

**Comment by reckerx** [comment]
@dl2n Thanks for the Input. 

I would like to share some more details regarding the commands used and how we did trace analysis.

Attaching the DiskSPD output file for the input command

` Command Line: diskspd -b32k -c100m -o32 -t1 -d10 -W0 -s -h -w100 -L F:\TestData.dat `

after performing this, i expect diskspd to write the data to drive in 32K block size chunks. 
But through solid gear protocol analyzer, only 10% of the total 100MB data is written at 32K Block Size. 

Attaching the reference Image for the Chunk Size IO distribution.

![bs32k](https://user-images.githubusercontent.com/26691990/39739844-a0fb7ace-52b0-11e8-8122-2be34a4e8a17.PNG)

In the above image, random chunks are distributed widely shown in the right most column. i was expecting 90-100% data to be written at 32K Blocksize as specified in the DiskSPD command. 

I even tried analyzing the data written to removable SD/uSD cards using Microsoft Message analyzer, it displays the "Bulk Out" Data correctly same as the DiskSPD input BlockSize. But the same data is written to SD/uSD Cards at random chunks. (Ref. Above image).

Considering all these, is it possible that 

> 1.	Since USB2.0 Port limits to 64KB Data per SCSI Command. So Each 512KB Access shall be split into 8 SCSI Commands of 64KB Data. ?? 
> 2.	USB3.0 Port limits the 512KB Data per SCSI Command.	Each 1MB Access shall be split into 2 SCSI Commands of 512KB Data ?
> 3.	USB3.1 Port limits to 1MB Data per SCSI Command. A 20 MB File might be split into 20 SCSI Commands of 1MB each ? 

Does these Statements answers the data being written in Random chunks?
Any suggestions regarding the tool to be used for monitoring at what Block Size data being written to drives and to capture the traces (Suggestions on any Hardware based Protocol Analyzers). ??

**Comment by dl2n** [comment]
Running with -c<size> always carries the risk of a surprise. I suspect you are not running as administrator and got a WARNING to that effect, that the file needed to be initialized prior to the test. When run as administrator, DISKSPD will create the file and advance the valid data length to EOF prior to operation. This avoids a pass of pre-writing the file to extend VDL with actual IO.

See [here](https://github.com/Microsoft/diskspd/blob/a796c20fda87a793b2032d31d253ded1fff29dbb/IORequestGenerator/IORequestGenerator.cpp#L1723) in the source.

That IO would be in 1MB units up to the last IO, aligned to file size. At that point you know much more than I do about the behavior of the USB stack.

I suggest running against or at least limiting what you measure to pre-existing files and see what you see. At that point any effects due to VDL should be gone and the rest is clean matter of how the lower stack between DISKSPD and the SD card handles your 32KiB IOs.

**Comment by dl2n** [comment]
Great.
