### ISSUE TITLE
diskspd does not measure write speed

### ISSUE THREAD

**Issue by MarcelTUC** [microsoft/diskspd#99]
I use diskspd to measure the performance of a network connection to a network storage.
For that, I need to measure upload (write) and download (read) performance of a file independently of each other. This seems simple to do via da -w100 or -w0 parameter. The performance of the storage is much higher than the performanceof the network connection.
Using the following command: `.\diskspd.exe -d30 -F1 -w100 -o1 -Sbwm -Z -Rtext \\Path\to\File\Speedtest\LargeBinaryStream.bst` diskspd downloads the file at first and then uploads the file. This behavior is correct and as expected. But the measurement measures at a wrong time.
![TaskManager](https://user-images.githubusercontent.com/14199524/57449378-03ee0900-725c-11e9-994c-2bb37c3bb6fa.JPG)
In the picture, you see a screenshot of the task manager performance graph of the notebook running diskspd. 
If I start the measurement (point "A"), diskspd begins its measurement and downloads the file for 30 seconds.
At point B diskspd stops the measurement, shows me the results and the .exe is closed (see Powershell screenshot). Then a system process begins to upload the file for 30 seconds (until point C). But there are no measurements anymore.
![PowerShell](https://user-images.githubusercontent.com/14199524/57449361-f6d11a00-725b-11e9-83a1-4a947814baaa.JPG)

Finally: Is this a bug? Did I something wrong in my diskspd parameters?

**Comment by dl2n** [comment]
What is your intent by adding the 'm' mode of operation with -Sbwm?

Memory mapped mode is intended as a mode of operation for persistent memory devices. The write-through intent changes to one appropriate for those devices, which is a flush from processor to memory, not memory to underlying filesystem store (which doesn't apply for persistent memory).

As is, what's happening is that the writes are persisted to memory, and then per normal delayed writeback of cached dirty data, that flows lazily after the file is closed, asynchronous to your foreground operations in DISKSPD.

I suspect you simply wanted buffered write-through, which would be -Sbw (no m).

**Comment by MarcelTUC** [comment]
The reason why I former used the -m parameter was: If I use only -Sbw, I get a write speed of 100 megabit/s´. If I copy the testfile with the windows explorer, I get a write speed of 400 megabits/s. Following that I assumed that parameter constellation would be more natural "explorer like".
So what are the correct parameters to measure the speed that the explorer shows during copy?

**Comment by dl2n** [comment]
If you want to look at the behavior of explorer: use explorer. DISKSPD is a simple microbenchmark and may not necessarily be able to reproduce the specific behavior of a full workload, even one as apparently simple as explorer’s file copy.

Explorer does not use memory mapped IO.

There are a number of things you can do to get things to go faster – more threads, more IO queued (<- more likely similar to explorer, up to 4 or so), different/larger IO sizes (<- larger ones up to 1MiB will be more similar), etc. Getting closer to a given speed does not mean you’ve reproduced explorer’s behavior, though.

If you really are after explorer copy, it turns out there is a common copy file engine underlying essentially all tooling which copies files in Windows. It turns out to be significantly more complex than just a “copy”: alternate data streams, security, et.al.).

https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-copyfile

This means you can use the cmd xcopy, robocopy, et.al. and be exercising the same engine. It does mean you will need to have a source as well as the destination file, but it will be correct.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
[HxS - 18362 - 16.0.11629.20164]

________________________________
